### ISSUE TITLE
Cannot click or scroll when viewing office documents

### ISSUE THREAD

**Issue by jiaming233** [vuplex/hololens-webview-example#2]
Hi, I try to open online office documents with your asset via "https://view.officeapps.live.com/op/view.aspx?src="

It works great on PC and Android, but when I deploy the project to Hololens 2, click and scroll don't work. 

By the way, click and scroll work on all platforms when I open common webpage like "google".

Do you have any clue about this? Thanks!

**Comment by binarynate** [comment]
Hi, @jiaming233 👋. Thank you for using 3D WebView, and I'm sorry for the inconvenience! I just sent you a response to the message you sent through the [Vuplex contact page](https://support.vuplex.com/contact). Thanks for sending that message—that's the right place to send support requests for 3D WebView. If you have other questions, please respond to my email. As a reference in case others encounter this issue in the future, here's the response I sent you:

> I looked into this and found that this issue occurs because the Office web apps are loaded inside an HTML [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) element. 3D WebView for UWP uses the [UWP WebView control](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview?view=winrt-22000) as its browser engine. The UWP WebView control doesn't provide a native API for triggering mouse events, so 3D WebView uses JavaScript to trigger clicks and scrolling in the page. Unfortunately, the UWP WebView control also doesn't provide an API to run JavaScript inside an iframe element, so when running in the 3D rendering mode, 3D WebView is unable to click or scroll web content hosted inside of an iframe. I'm tracking this issue, and I added you to its waitlist so that I'll send you an update if this changes in the future. I'll also update the product page to list this limitation.
